### ISSUE TITLE
CustomInventory->click has 2 source item parameters

### ISSUE THREAD

**Issue by NickteeChunky** [tedo0627/InventoryUI#1]
Not really sure why no one's pointed this out yet but the click function has a sourceItem and a targetItem parameter but in EventListener:
https://github.com/tedo0627/InventoryUI/blob/5a531852c492be31eac9989bdd1650e0011c3fe0/src/tedo0627/inventoryui/EventListener.php#L35
It's just getSourceItem() twice

**Comment by tedo0627** [comment]
True, I hadn't noticed.
